### ISSUE TITLE
Deleting the current menu item causes the app to get stuck in an error loop

### ISSUE THREAD

**Issue by stuaxo** [bluesabre/menulibre#71] opened 2020-12-09 16:24 UTC
To reproduce:  View a menu item, then delete its desktop file in the commandline.

What happens: An error is displayed, and then it returns when you press a button.

What should happen:   The error should be displayed only once, after that the item should probably disappear from the items in the app.

**Comment by bluesabre** [comment] 2022-09-27 11:05
Duplicate of https://github.com/bluesabre/menulibre/issues/70

**Closed by bluesabre** 2022-09-27 11:05 UTC
Labels: New
